=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'

# Unit tests for MuxRuby::ErrorsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ErrorsApi' do
  before do
    # run before each test
    @instance = MuxRuby::ErrorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorsApi' do
    it 'should create an instance of ErrorsApi' do
      expect(@instance).to be_instance_of(MuxRuby::ErrorsApi)
    end
  end

  # unit tests for list_errors
  # List Errors
  # Returns a list of errors 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filters Filter key:value pairs. Must be provided as an array query string parameter (e.g. filters[]&#x3D;operating_system:windows&amp;filters[]&#x3D;country:US).  Possible filter names are the same as returned by the List Filters endpoint. 
  # @option opts [Array<String>] :timeframe Timeframe window to limit results by. Must be provided as an array query string parameter (e.g. timeframe[]&#x3D;). Accepted formats are...   * array of epoch timestamps e.g. timeframe[]&#x3D;1498867200&amp;timeframe[]&#x3D;1498953600    * duration string e.g. timeframe[]&#x3D;24:hours or timeframe[]&#x3D;7:days. 
  # @return [ListErrorsResponse]
  describe 'list_errors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
