=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'

# Unit tests for MuxRuby::ExportsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExportsApi' do
  before do
    # run before each test
    @instance = MuxRuby::ExportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExportsApi' do
    it 'should create an instance of ExportsApi' do
      expect(@instance).to be_instance_of(MuxRuby::ExportsApi)
    end
  end

  # unit tests for list_exports
  # List property video view export links
  # Lists the available video view exports along with URLs to retrieve them 
  # @param [Hash] opts the optional parameters
  # @return [ListExportsResponse]
  describe 'list_exports test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
