=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'

# Unit tests for MuxRuby::IncidentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IncidentsApi' do
  before do
    # run before each test
    @instance = MuxRuby::IncidentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IncidentsApi' do
    it 'should create an instance of IncidentsApi' do
      expect(@instance).to be_instance_of(MuxRuby::IncidentsApi)
    end
  end

  # unit tests for get_incident
  # Get an Incident
  # Returns the details of an incident 
  # @param incident_id ID of the Incident
  # @param [Hash] opts the optional parameters
  # @return [IncidentResponse]
  describe 'get_incident test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_incidents
  # List Incidents
  # Returns a list of incidents 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of items to include in the response
  # @option opts [Integer] :page Offset by this many pages, of the size of &#x60;limit&#x60;
  # @option opts [String] :order_by Value to order the results by
  # @option opts [String] :order_direction Sort order.
  # @option opts [String] :status Status to filter incidents by
  # @option opts [String] :severity Severity to filter incidents by
  # @return [ListIncidentsResponse]
  describe 'list_incidents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_related_incidents
  # List Related Incidents
  # Returns all the incidents that seem related to a specific incident 
  # @param incident_id ID of the Incident
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of items to include in the response
  # @option opts [Integer] :page Offset by this many pages, of the size of &#x60;limit&#x60;
  # @option opts [String] :order_by Value to order the results by
  # @option opts [String] :order_direction Sort order.
  # @return [ListRelatedIncidentsResponse]
  describe 'list_related_incidents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
