=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'

# Unit tests for MuxRuby::URLSigningKeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'URLSigningKeysApi' do
  before do
    # run before each test
    @instance = MuxRuby::URLSigningKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of URLSigningKeysApi' do
    it 'should create an instance of URLSigningKeysApi' do
      expect(@instance).to be_instance_of(MuxRuby::URLSigningKeysApi)
    end
  end

  # unit tests for create_url_signing_key
  # Create a URL signing key
  # Creates a new signing key pair. When creating a new signing key, the API will generate a 2048-bit RSA key-pair and return the private key and a generated key-id; the public key will be stored at Mux to validate signed tokens. 
  # @param [Hash] opts the optional parameters
  # @return [SigningKeyResponse]
  describe 'create_url_signing_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_url_signing_key
  # Delete a URL signing key
  # Deletes an existing signing key. Use with caution, as this will invalidate any existing signatures and no URLs can be signed using the key again. 
  # @param signing_key_id The ID of the signing key.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_url_signing_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_url_signing_key
  # Retrieve a URL signing key
  # Retrieves the details of a URL signing key that has previously been created. Supply the unique signing key ID that was returned from your previous request, and Mux will return the corresponding signing key information. **The private key is not returned in this response.** 
  # @param signing_key_id The ID of the signing key.
  # @param [Hash] opts the optional parameters
  # @return [SigningKeyResponse]
  describe 'get_url_signing_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_url_signing_keys
  # List URL signing keys
  # Returns a list of URL signing keys. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of items to include in the response
  # @option opts [Integer] :page Offset by this many pages, of the size of &#x60;limit&#x60;
  # @return [ListSigningKeysResponse]
  describe 'list_url_signing_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
