=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::AssetStaticRenditionsFiles
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetStaticRenditionsFiles' do
  before do
    # run before each test
    @instance = MuxRuby::AssetStaticRenditionsFiles.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetStaticRenditionsFiles' do
    it 'should create an instance of AssetStaticRenditionsFiles' do
      expect(@instance).to be_instance_of(MuxRuby::AssetStaticRenditionsFiles)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["low.mp4", "medium.mp4", "high.mp4"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.name = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "ext"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["mp4"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.ext = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "height"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "width"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "bitrate"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "filesize"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
