=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::AssetMaster
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetMaster' do
  before do
    # run before each test
    @instance = MuxRuby::AssetMaster.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetMaster' do
    it 'should create an instance of AssetMaster' do
      expect(@instance).to be_instance_of(MuxRuby::AssetMaster)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ready", "preparing", "errored"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
