=begin
# Mux Ruby - Copyright 2019 Mux Inc.
# NOTE: This file is auto generated. Do not edit this file manually.
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::InputSettingsOverlaySettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InputSettingsOverlaySettings' do
  before do
    # run before each test
    @instance = MuxRuby::InputSettingsOverlaySettings.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InputSettingsOverlaySettings' do
    it 'should create an instance of InputSettingsOverlaySettings' do
      expect(@instance).to be_instance_of(MuxRuby::InputSettingsOverlaySettings)
    end
  end
  describe 'test attribute "vertical_align"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["top", "middle", "bottom"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.vertical_align = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "vertical_margin"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "horizontal_align"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["left", "center", "right"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.horizontal_align = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "horizontal_margin"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "width"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "height"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "opacity"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
