=begin
#Mux API

#Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.

The version of the OpenAPI document: v1
Contact: devex@mux.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::ReferrerDomainRestriction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MuxRuby::ReferrerDomainRestriction do
  let(:instance) { MuxRuby::ReferrerDomainRestriction.new }

  describe 'test an instance of ReferrerDomainRestriction' do
    it 'should create an instance of ReferrerDomainRestriction' do
      expect(instance).to be_instance_of(MuxRuby::ReferrerDomainRestriction)
    end
  end
  describe 'test attribute "allowed_domains"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allow_no_referrer"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
