=begin
#Mux API

#Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.

The version of the OpenAPI document: v1
Contact: devex@mux.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::SpaceStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MuxRuby::SpaceStatus do
  let(:instance) { MuxRuby::SpaceStatus.new }

  describe 'test an instance of SpaceStatus' do
    it 'should create an instance of SpaceStatus' do
      expect(instance).to be_instance_of(MuxRuby::SpaceStatus)
    end
  end
end
