=begin
#Mux API

#Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.

The version of the OpenAPI document: v1
Contact: devex@mux.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MuxRuby::UpdateLiveStreamNewAssetSettings
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MuxRuby::UpdateLiveStreamNewAssetSettings do
  let(:instance) { MuxRuby::UpdateLiveStreamNewAssetSettings.new }

  describe 'test an instance of UpdateLiveStreamNewAssetSettings' do
    it 'should create an instance of UpdateLiveStreamNewAssetSettings' do
      expect(instance).to be_instance_of(MuxRuby::UpdateLiveStreamNewAssetSettings)
    end
  end
  describe 'test attribute "mp4_support"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "standard", "capped-1080p", "audio-only", "audio-only,capped-1080p"])
      # validator.allowable_values.each do |value|
      #   expect { instance.mp4_support = value }.not_to raise_error
      # end
    end
  end

end
