name: Integration Test v2

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Integration Test v2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
        env:
          MUX_TOKEN_ID: ${{ secrets.MUX_TOKEN_ID }}
          MUX_TOKEN_SECRET: ${{ secrets.MUX_TOKEN_SECRET }}
      - run: bash test.sh
